config/routes.rb
Rails.application.routes.draw do

  resources :job_applications
  resources :jobs
  mount Ckeditor::Engine => '/ckeditor'
  resources :reviews

  get 'referrals/download' => 'referrals#download'
  get 'referrals/processed' => 'referrals#processed_referrals', as: :processed_referrals
  delete "referrals" => "referrals#destroy_all"
  resources :referrals

  resources :news_releases

  get 'appointments/download' => 'appointments#download'
  get 'appointments/processed' => 'appointments#processed_appointments', as: :processed_appointments
  delete "appointments" => "appointments#destroy_all"

  resources :appointments
  resources :contacts

  post "experts/sort" => "experts#sort"

  resources :experts
  resource :session
  resources :users
  resources :pages
  root 'pages#home'
  get 'dashboard' => 'pages#dashboard'
  get 'clinical_trials_dashboard' => 'pages#clinical_trials_dashboard'
  get 'search' => 'pages#search'

  get 'admin/news_releases' => 'admin/news_releases#index', as: :admin_news_releases
  delete 'admin/news_release/:id' => 'admin/news_releases#destroy', as: :admin_news_release

  namespace :admin do
    resources :slides
  end

  
  

end

app/models/slide.rb
class Slide < ActiveRecord::Base
	has_attached_file :photo,
    styles: { large: "940x355>", thumb: "235x90>" },
		:storage => :s3,
		:s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":attachment/:id/:style.:extension",
    :s3_protocol => :https,
    :s3_host_name => "s3.us-east-1.amazonaws.com",
    :url => ":s3_host_name"

	validates_attachment :photo,
		:content_type => { :content_type => ['image/jpeg', 'image/png'] },
		:size => { :less_than => 1.megabyte }

  scope :by_position, -> { order(:position) }
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  before_action :get_slide, only: [:edit, :update, :destroy]

  def index
    @slides = Slide.by_position
  end

  def new
    @slide = Slide.new
  end

  def create
    @slide = Slide.new(slide_params)

    if @slide.save
      flash[:notice] = "Slide successfully created!"
      redirect_to admin_slides_path
    else
      flash[:alert] = "There were some errors, see below"
      render :new
    end
  end

  def edit
  end

  def update
    if @slide.update_attributes(slide_params)
      flash[:notice] = "Slide successfully updated!"
      redirect_to admin_slides_path
    else
      flash[:alert] = "There were some errors, see below"
      render :edit
    end
  end

  def destroy
    @slide.destroy
    flash[:notice] = "Slide successfully deleted!"
    redirect_to admin_slides_path
  end

  private

  def slide_params
    params.require(:slide).permit(:title, :description, :position, :link_url, :link_title, :photo)
  end

  def get_slide
    @slide = Slide.find(params[:id])
  end
end

app/views/admin/slides/_form.html.erb
<%= form_for [:admin, @slide], multipart: true do |f| %>
  <%= render "shared/errors", object: @slide %>

  <div class="group">
    <div style="float: left;">
      <%= f.label :photo, "Photo" %>
      <%= f.file_field :photo %>
        <p>
          <em>Slide background photo</em>
        </p>
    </div>
    <%= image_tag @slide.photo.url(:thumb), style: "float: right;" %>
  </div>

  <p>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
    <em>Max. 45 characters</em>
  </p>

  <p>
  <%= f.label :description %>
  <%= f.text_area :description %>
    <em>Max. 230 characters</em>
  </p>

  <p>
  <%= f.label :link_title %>
  <%= f.text_field :link_title %><br>
    <em>Title for  the link button. Max. 40 characters</em>
  </p>

  <p>
  <%= f.label :link_url %>
  <%= f.text_field :link_url %><br>
    <em>Full URL of the linked page (example: http://uoc.com/pages/services)</em>
  </p>

  <p>
  <%= f.label :position %>
  <%= f.text_field :position %><br>
    <em>Position of the slide in the carousel</em>
  </p>

    <p>
      <%= f.submit class: "green-link" %>
    </p>
<% end %>

app/views/admin/slides/edit.html.erb
<div class="main-content-wide">
  <h1>Edit Slide</h1>

  <%= render 'form' %>

  <%= link_to "Cancel", admin_slides_path, class: 'gray-link' %>
</div>

app/views/admin/slides/index.html.erb
<div class="main-content-wide">
  <h1><%= pluralize(@slides.count, 'Slide') %></h1>

  <% @slides.each do |slide| %>
    <div class="appointment-list">
      <%= link_to "Delete", admin_slide_path(id: slide.id),
        method: :delete,
        data: {confirm: "Are you sure you want to permanently delete this slide?"},
        class: "gray-link", style: "float:right",
        id: "slide-#{slide.id}" %>

      <%= link_to "Edit", edit_admin_slide_path(id: slide.id), class: "green-link", style: "float:right" %>
      <%= image_tag slide.photo.url(:thumb) %>
      <h2><%= slide.title %></h2>
      <p>
        <%= slide.description %>
      </p>
    </div>
  <% end %>

  <%= link_to "New Slide", new_admin_slide_path, class: 'green-link' %>
</div>

app/views/admin/slides/new.html.erb
<div class="main-content-wide">
  <h1>New Slide</h1>

  <%= render 'form' %>

  <%= link_to "Cancel", admin_slides_path, class: 'gray-link' %>
</div>