config/routes.rb
Rails.application.routes.draw do

  resources :job_applications
  resources :jobs
  mount Ckeditor::Engine => '/ckeditor'
  resources :reviews

  get 'referrals/download' => 'referrals#download'
  get 'referrals/processed' => 'referrals#processed_referrals', as: :processed_referrals
  delete "referrals" => "referrals#destroy_all"
  resources :referrals

  resources :news_releases

  get 'appointments/download' => 'appointments#download'
  get 'appointments/processed' => 'appointments#processed_appointments', as: :processed_appointments
  delete "appointments" => "appointments#destroy_all"

  resources :appointments
  resources :contacts

  post "experts/sort" => "experts#sort"

  resources :experts
  resource :session
  resources :users
  resources :pages
  root 'pages#home'
  get 'dashboard' => 'pages#dashboard'
  get 'clinical_trials_dashboard' => 'pages#clinical_trials_dashboard'
  get 'search' => 'pages#search'

  get 'admin/news_releases' => 'admin/news_releases#index', as: :admin_news_releases
  delete 'admin/news_release/:id' => 'admin/news_releases#destroy', as: :admin_news_release

  namespace :admin do
    resources :slides
  end

  
  

end

app/views/pages/_admin_links.html.erb
<ul class="dashboard-list">
  <li>
    <%= link_to "Experts", experts_path %>
    <ul>
      <li><%= link_to "Physicians", experts_path(category: :physicians) %></li>
      <li><%= link_to "Physicians Assistants", experts_path(category: :physicians_assistants) %></li>
      <li><%= link_to "Physical Therapists", experts_path(category: :physical_therapists) %></li>
      <li><%= link_to "Clinical Researchers", experts_path(category: :clinical_researchers) %></li>
      <li><%= link_to "Worker's Comp", experts_path(category: :workers_comp) %></li>
      <li><%= link_to "Athletic Trainers", experts_path(category: :athletic_trainers) %></li>
      <li><%= link_to "Joint Replacement Coordinator", experts_path(category: :joint_replacement) %></li>
      <li><%= link_to "Neuropsychologist", experts_path(category: :neuropsychologist) %></li>
      <li><%= link_to "Create New Expert", new_expert_path %></li>
    </ul>
  </li>

  <li>
    <%= link_to "News", admin_news_releases_path %>
    <ul>
      <li><%= link_to "Create News Release", new_news_release_path %></li>
    </ul>
  </li>

  <li><%= link_to "Appointment Requests", appointments_path %>
    <ul>
      <li><%= link_to "Saved Appointments", processed_appointments_path %></li>
    </ul>
  </li>

  <li><%= link_to "Referrals", referrals_path %>
    <ul>
      <li><%= link_to "Saved Referrals", processed_referrals_path %></li>
    </ul>
  </li>

  <li><%= link_to "Job Listings", jobs_path %> </li>

  <li><%= link_to "Job Applications", job_applications_path %> </li>

  <li><%= link_to "Patient Reviews", reviews_path %> </li>

  <li><%= link_to "Slides", admin_slides_path  %> </li>
</ul>

app/views/pages/_box_portal.html.erb
<div class="home-box with-header" style="padding-bottom: .8em">
  <h2 class="roboto">Patient Portal</h2>
  <p class="tight">
  Access your patient records<br>and pay bills online 24/7.
  </p>
  <%= link_to "Learn more",  
    page_path('what-is-nextmd'),
    class: "green-link green-link-centered" %>
</div>

app/views/pages/_box_sports.html.erb
<div class="home-col box-with-photo">
  <h2 class="roboto">Sports Medicine</h2>

  <div class="box-within">
    <p>
    It’s a long season. Stay in the game kickoff to playoff.
    </p> 
    <%= link_to "Find out how", page_path("sports-medicine-services"), class: "green-link green-link-centered" %>
  </div>
</div>

app/views/pages/_careers.html.erb
<% unless @jobs.empty? %>
<h2>Job Openings</h2>

<ol style="padding-left: 1.5em;">
<% @jobs.each do |job| %>
  <li><b><%= link_to job.name, new_job_application_path(job_id: job.id) %></b> <%= job.description %></li>
<% end %>
</ol>
<% end %>

app/views/pages/_clinical_trials_links.html.erb
<ul class="dashboard-list clinical-trials">
  <li id="clinical-trials-edit"><%= link_to 'Clinical Trials', page_path('clinical-trials') %>
  <%= link_to "Edit", edit_page_path('clinical-trials'), class: 'edit-link' %>
    <ul>
      <li id="altoona-edit"><%= link_to 'Altoona', page_path('trials-altoona-fairway') %>
      <%= link_to "Edit", edit_page_path('trials-altoona-fairway'), class: 'edit-link' %>
      </li>
      <li id="state-college-edit"><%= link_to 'State College', page_path('trials-state-college') %>
      <%= link_to "Edit", edit_page_path('trials-state-college'), class: 'edit-link' %>
      </li>
    </ul>
  </li>
</ul>

app/views/pages/_mobile_box_pain.html.erb
<div class="home-col box-empty">
<div class="mobile-home-box">
  <h2>Pain Information Center</h2>
  <p>
  Where does it hurt?
  </p> 

  <ul class="hurts">
    <li><%= link_to "Neck", page_path("neck-back") %></li>
    <li><%= link_to "Back", page_path("neck-back") %></li>
    <li><%= link_to "Shoulder", page_path("shoulders") %></li>
    <li><%= link_to "Elbow", page_path("elbows") %></li>
    <li><%= link_to "Hand", page_path("hands-wrists") %></li>
  </ul>

  <ul class="hurts">
    <li><%= link_to "Hip", page_path("hips") %></li>
    <li><%= link_to "Knee", page_path("knees") %></li>
    <li><%= link_to "Ankle", page_path("feet-ankles") %></li>
    <li><%= link_to "Foot", page_path("feet-ankles") %></li>
  </ul>
</div>
</div>

app/views/pages/_mobile_box_sports.html.erb
<div class="home-col mobile-home-box mobile-box-with-photo">
  <h2>Sports Medicine</h2>

  <div class="bottom-box">
    <p>
    It’s a long season. Stay in the game kickoff to playoff.
    </p> 
    <%= link_to "Find out how", page_path("sports-medicine-services"), class: "green-link green-link-centered" %>
  </div>
</div>

app/views/pages/_refer_a_patient.html.erb
<%= form_for @referral do |f| %>
<%= render "shared/errors", object: @referral %>

<h2>Referring Office Contact Information</h2>
  <div class="form-row group">
    <div class="half-row">
      <%= f.label :practice, "Practice" %>
      <%= f.text_field :practice %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :physician, "Referring Physician" %>
      <%= f.text_field :physician %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :name, "Your Name" %>
      <%= f.text_field :name %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :phone, "Phone Number" %>
      <%= f.text_field :phone %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :email, "Email Address" %>
      <%= f.text_field :email %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :fax, "Fax Number <span class='opt'>(optional)</span>".html_safe %>
      <%= f.text_field :fax %>
      <p class="opt">
        If you would like a confirmation of your patient’s appointment, please provide a fax number.
      </p>
    </div>
  </div>

  <h2>Patient Information</h2>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :patient_name, "Patient Name" %>
      <%= f.text_field :patient_name %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :dob, "Date of Birth" %>
      <%= f.text_field :dob %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :patient_phone, "Patient Phone Number" %>
      <%= f.text_field :patient_phone %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :patient_phone_alt,
        "Patient Alternate Phone Number <span class='opt'>(optional)</span>".html_safe %>
      <%= f.text_field :patient_phone_alt %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :patient_email, "Patient Email Address" %>
      <%= f.text_field :patient_email %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :employer, "Employer" %>
      <%= f.text_field :employer %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :insurance, "Patient Insurance" %>
      <%= f.text_field :insurance %>
    </div>
  </div>

  <div class="form-row group">
    <%= f.label :diagnosis, "Symptoms & Diagnosis" %>
    <%= f.text_area :diagnosis %>
  </div>

  <div class="form-row group">
    <div class="half-row">
      <label>Has the patient had a prior surgery (to the same body part)?</label>
      <%= f.radio_button :prior_surgery, true %>
      <%= f.label :prior_surgery, "Yes", class: "inline" %>

      <%= f.radio_button :prior_surgery, false %>
      <%= f.label :prior_surgery, "No", class: "inline" %>
    </div>
    <div class="half-row with-gutter">
      <label>Was this injury/condition related to Workers' Compensation?</label>
      <%= f.radio_button :workers_comp, true %>
      <%= f.label :workers_comp, "Yes", class: "inline" %>

      <%= f.radio_button :workers_comp, false %>
      <%= f.label :workers_comp, "No", class: "inline" %>
    </div>
  </div>



<h3>Patient Has Completed</h3>

  <div class="form-row group">
    <div class="half-row with-top-padding">
      <%= f.check_box :bone_scan %>
      <%= f.label :bone_scan, "Bone Scan", class: "inline" %>
    </div>
    <div class="half-row">
      <%= f.label :bone_scan_where, "Where/When?" %>
      <%= f.text_field :bone_scan_where %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row with-top-padding">
      <%= f.check_box :ct_scan %>
      <%= f.label :ct_scan, "CT Scan", class: "inline" %>
    </div>
    <div class="half-row">
      <%= f.label :ct_scan_where, "Where/When?" %>
      <%= f.text_field :ct_scan_where %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row with-top-padding">
      <%= f.check_box :mri %>
      <%= f.label :mri, "MRI", class: "inline" %>
    </div>
    <div class="half-row">
      <%= f.label :mri_where, "Where/When?" %>
      <%= f.text_field :mri_where %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row with-top-padding">
      <%= f.check_box :emg %>
      <%= f.label :emg, "EMG", class: "inline" %>
    </div>
    <div class="half-row">
      <%= f.label :emg_where, "Where/When?" %>
      <%= f.text_field :emg_where %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row with-top-padding">
      <%= f.check_box :x_rays %>
      <%= f.label :x_rays, "X-Rays", class: "inline" %>
    </div>
    <div class="half-row">
      <%= f.label :x_rays_where, "Where/When?" %>
      <%= f.text_field :x_rays_where %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row with-top-padding">
      <%= f.check_box :cast %>
      <%= f.label :cast, "Cast/Splint Applied", class: "inline" %>
    </div>
    <div class="half-row">
      <%= f.label :cast_where, "Where/When?" %>
      <%= f.text_field :cast_where %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :preferred_physician, "Preferred Physician" %>
      <%= f.select :preferred_physician, Referral::PHYSICIANS, {include_blank: "None"}   %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :preferred_office, "Office Preference" %>
      <%= f.select :preferred_office, Referral::OFFICES, {include_blank: "No Preference"}   %>
    </div>
  </div>

  <div class="form-row group">
    <label> Requested time to be seen </label>
    <div class="half-row">
      <%= f.radio_button :time_to_be_seen, "1_day" %>
      <%= f.label :time_to_be_seen, "1-2 days", class: "inline" %>

      <%= f.radio_button :time_to_be_seen, "3_days" %>
      <%= f.label :time_to_be_seen, "3-5 days", class: "inline" %>
    </div>
  </div>

  <div class="form-row group with-top-padding">
    <%= f.submit "Submit", class: "green-link" %>
  </div>

<% end %>

app/views/pages/_reviews.html.erb
<div class="home-box with-header" style="padding-bottom: 11px">
  <h2 class="roboto">
    <%= link_to "Reviews &amp; Testimonials".html_safe, page_path('patient-reviews'), class: 'white-link' %>
  </h2>
  <p class="tight">Read our patient’s comeback stories or write your own review.</p>
  <%= link_to "Get started", page_path("submit-review"), class: "green-link green-link-centered" %>
</div>

app/views/pages/_submit_review.html.erb
<%= form_for @review do |f| %>

<%= render "shared/errors", object: @review %>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name %>
      <%= f.text_field :address, class: "form_address"  %>
    </div>
  </div>

  <div class="form-row group">
    <div class="half-row">
      <%= f.label :email, "Email Address" %>
      <%= f.email_field :email %>
    </div>
    <div class="half-row with-gutter">
      <%= f.label :phone, "Phone Number" %>
      <%= f.text_field :phone %>
    </div>
  </div>

  <div class="form-row group">
    <%= f.label :message, "Share your story" %>
    <%= f.text_area :message %>
  </div>

  <div class="form-row group">
    <%= f.submit "Submit", class: "green-link" %>
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<div class="main-content-wide">
<h1>Dashboard</h1>

<% if current_user.clinical_trials? %>
  <%= render 'clinical_trials_links' %>
<% else %>
  <%= render 'admin_links' %>
<% end %>

</div>

app/views/pages/edit.html.erb
<div class="main-content-wide">
  <h1>Editing</h1>
  <h2><%= @page.title %></h2>

  <%= form_for @page, multipart: true do |f| %>
    <%= render "shared/errors", object: @page %>
    <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
    </p>

    <p>
    <%= f.label :body %>
    <%= f.cktext_area :body, ckeditor: {height: 600} %>
    </p>

    <p>
    <%= f.label :label, "Label" %>
    <%= f.text_field :label %>
    <em>Label that appears in the navigation links</em>
    </p>

    <div class="group">
      <div style="float: left;">
        <%= f.label :main_image, "Main Image" %>
        <%= f.file_field :main_image %>
          <p>
            <em>Image at top of the page</em>
          </p>
      </div>
      <%= image_tag @page.main_image.url, style: "float: right;width:50%;" %>
    </div>

    <div class="edit-form-row">
        <label>Publish page?</label>
        <%= f.radio_button :publish, true %>
        <%= f.label :publish, "Yes", class: "inline" %>

        <%= f.radio_button :publish, false %>
        <%= f.label :publish, "No", class: "inline" %>
    </div>

    <p>
    <%= f.label :seo_title, "SEO Title" %>
    <%= f.text_field :seo_title %>
    </p>
    <p>
    <%= f.label :seo_description, "SEO Description" %>
    <%= f.text_area :seo_description %>
    </p>
    <p>
    <%= f.label :seo_keywords, "SEO Keywords" %>
    <%= f.text_field :seo_keywords %>
    </p>

    <p>
      <%= f.submit "Update Page", class: "green-link" %>
    </p>

  <% end %>
</div>

app/views/pages/home.html.erb
<%= render "layouts/slideshow" %>

<div class="home-boxes">
  <% if mobile_device? %>
    <%= render "/pages/mobile_box_pain" %>
  <% else %>
    <%= render "/pages/box_pain" %>
  <% end %>

  <% if mobile_device? %>
    <%= render "/pages/mobile_box_sports" %>
  <% else %>
    <%= render "/pages/box_sports" %>
  <% end %>

  <div class="home-col box-empty">
    <% if mobile_device? %>
      <%= render "/pages/mobile_box_portal" %>
      <%= render "/pages/mobile_reviews" %>
    <% else %>
      <%= render "/pages/box_portal" %>
      <%= render "/pages/reviews" %>
    <% end %>
  </div>

</div>

app/views/pages/search.html.erb
<nav class="side-navigation">
  <h2 class="roboto">Search</h2>
</nav>

<div class="main-content">

<%= image_tag "service_photo.jpg" %>
<h1 class="roboto">Search</h1>

<p>
  Enter the term you are looking for in the box below.
</p>

<div id="search-div">
  <script>
  (function() {
    var cx = '006084191273836075856:9tzzzsdpkgi';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
    })();
  </script>
  <gcse:search></gcse:search>
</div>

</div>