config/routes.rb
Rails.application.routes.draw do

  resources :job_applications
  resources :jobs
  mount Ckeditor::Engine => '/ckeditor'
  resources :reviews

  get 'referrals/download' => 'referrals#download'
  get 'referrals/processed' => 'referrals#processed_referrals', as: :processed_referrals
  delete "referrals" => "referrals#destroy_all"
  resources :referrals

  resources :news_releases

  get 'appointments/download' => 'appointments#download'
  get 'appointments/processed' => 'appointments#processed_appointments', as: :processed_appointments
  delete "appointments" => "appointments#destroy_all"

  resources :appointments
  resources :contacts

  post "experts/sort" => "experts#sort"

  resources :experts
  resource :session
  resources :users
  resources :pages
  root 'pages#home'
  get 'dashboard' => 'pages#dashboard'
  get 'clinical_trials_dashboard' => 'pages#clinical_trials_dashboard'
  get 'search' => 'pages#search'

  get 'admin/news_releases' => 'admin/news_releases#index', as: :admin_news_releases
  delete 'admin/news_release/:id' => 'admin/news_releases#destroy', as: :admin_news_release

  namespace :admin do
    resources :slides
  end

  
  

end

app/controllers/admin/news_releases_controller.rb
class Admin::NewsReleasesController < ApplicationController
  before_action :require_signin
  before_action :require_admin

  def index
    @news_releases = NewsRelease.order(created_at: :desc).
      paginate(page: params[:page], per_page: 30)
  end

  def destroy
    @news_release = NewsRelease.find(params[:id])
    @news_release.destroy
    redirect_to admin_news_releases_url, notice: 'News Release successfully removed!'
  end
end

app/controllers/news_releases_controller.rb
class NewsReleasesController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @news_releases = NewsRelease.published.order(created_at: :desc).paginate(page: params[:page])
  end

  def show
    if NewsRelease.find(params[:id]).published?
      @news_release = NewsRelease.find(params[:id])
    else
      if current_user_admin?
        @news_release = NewsRelease.find(params[:id])
      else
        redirect_to news_releases_url
      end
    end
  end

  def new
    @news_release = NewsRelease.new
  end

  def create
    @news_release = NewsRelease.new(news_release_params)
    if @news_release.save
      flash[:notice] = "News Release created correctly!"
      redirect_to @news_release
    else
      flash[:alert] = "There were some errors, see below"
      render :new
    end
  end

  def edit
    @news_release = NewsRelease.find(params[:id])
  end

  def update
    @news_release = NewsRelease.find(params[:id])
    if @news_release.update_attributes(news_release_params)
      redirect_to @news_release, notice: "News Release updated correctly!"
    else
      flash[:alert] = "There were some errors, see below"
      render :edit
    end
  end

  private

  def news_release_params
    params.require(:news_release).permit(:title, :body, :published, :youtube_id)
  end
end

app/helpers/news_releases_helper.rb
module NewsReleasesHelper
  def recent_news
    content_tag :ul, class: "news-side-list" do
      NewsRelease.published.recent.each do |news|
        concat(content_tag(:li, link_to(news.title, news)))
      end
    end
  end

  def published_label_for(release)
    if release.published?
      content_tag(:span, 'Published', class: 'admin-label green')
    else
      content_tag(:span, 'Unpublished', class: 'admin-label yellow')
    end
  end
end

app/views/news_releases/_form.html.erb
<%= form_for @news_release do |f| %>
  <%= render "shared/errors", object: @news_release %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.cktext_area :body %>
  </p>

  <div class="youtube-video-box">
    <p>
    <%= f.label :youtube_id, 'YouTube ID' %>
    <%= f.text_field :youtube_id %>
    <i>You can find the video YouTube ID in the "Share" box, in the YouTube page for the specific video. It would look similar to this:  _GZlUextcAA</i>
    </p>

    <%= image_tag 'youtube_window.png', class: 'youtube-window' %>
  </div>

  <p>
    <%= f.label :published %>
    <%= f.check_box :published %>
  </p>

  <p>
  <% if @news_release.new_record? %>
    <%= f.submit "Create News Release", class: "green-link" %>
  <% else %>
    <%= f.submit "Update News Release", class: "green-link" %>
  <% end %>
  </p>
<% end %>

app/views/news_releases/edit.html.erb
<div class="main-content-wide">
  <h1>Edit News Release</h1>
  <h2><%= @news_release.title %></h2>

  <%= render "form" %>
</div>

app/views/news_releases/index.html.erb
<nav class="side-navigation">
  <h2 class="roboto">News</h2>
  <p class="recent-news-title">
    Recent News
  </p>
  <%= recent_news %>
</nav>


<div class="main-content">
<% @news_releases.each do |news| %>
  <div class="news-block">
  <h3><%= news.created_at %></h3>
  <h2><%= link_to news.title, news %></h2>
  <%= news.tease %>
  <%= link_to "Read More", news, class: "more" %>
  </div>
<% end %>

<div class="apple-pagination">
<%= will_paginate @news %>
</div
</div>

app/views/news_releases/new.html.erb
<div class="main-content-wide">
  <h1>Create News Release</h1>
  <%= render "form" %>

</div>

app/views/news_releases/show.html.erb
<nav class="side-navigation">
  <h2 class="roboto">News</h2>
  <p class="recent-news-title">
    Recent News
  </p>
  <%= recent_news %>
</nav>


<div class="main-content">
  <div class="news-block">
    <h3><%= @news_release.created_at %></h3>
    <h2><%= @news_release.title %></h2>

    <hr size="1" noshade>
    <br>

    <%= @news_release.body.html_safe %>

    <% if @news_release.youtube_id.present? %>
      <iframe width="560" height="315" src='https://www.youtube.com/embed/<%= @news_release.youtube_id %>?rel=0&autoplay=0' frameborder='0' allowfullscreen></iframe>
    <% end %>


    <div class="social-media-icons">
      <%= social_share_button_tag(@news_release.title, desc: @news_release.title) %>
    </div>

    <% if current_user %>

      <% if current_user.admin? && !current_user.clinical_trials? %>
      <p>
        <%= link_to "Edit", edit_news_release_path(@news_release), class: "green-link edit-link" %>
        <%= link_to "Remove", [:admin, @news_release], method: :delete, data: { alert: "Are you sure"}, class: "green-link edit-link" %>
        <%= link_to "Back to News", admin_news_releases_path, class: "green-link edit-link" %>
      </p>
      <% end %>

    <% else %>
      <%= link_to "Back to News", news_releases_path, class: "more" %>
    <% end %>

  </div>

</div>