config/routes.rb
Rails.application.routes.draw do

  resources :job_applications
  resources :jobs
  mount Ckeditor::Engine => '/ckeditor'
  resources :reviews

  get 'referrals/download' => 'referrals#download'
  get 'referrals/processed' => 'referrals#processed_referrals', as: :processed_referrals
  delete "referrals" => "referrals#destroy_all"
  resources :referrals

  resources :news_releases

  get 'appointments/download' => 'appointments#download'
  get 'appointments/processed' => 'appointments#processed_appointments', as: :processed_appointments
  delete "appointments" => "appointments#destroy_all"

  resources :appointments
  resources :contacts

  post "experts/sort" => "experts#sort"

  resources :experts
  resource :session
  resources :users
  resources :pages
  root 'pages#home'
  get 'dashboard' => 'pages#dashboard'
  get 'clinical_trials_dashboard' => 'pages#clinical_trials_dashboard'
  get 'search' => 'pages#search'

  get 'admin/news_releases' => 'admin/news_releases#index', as: :admin_news_releases
  delete 'admin/news_release/:id' => 'admin/news_releases#destroy', as: :admin_news_release

  namespace :admin do
    resources :slides
  end

  
  

end

app/views/layouts/_admin_navigation.html.erb
<div class="admin-navigation group">
  <ul>
    <li><%= link_to "Dashboard", dashboard_path %></li>

    <% unless current_user.clinical_trials? %>
      <li><%= link_to "Experts", experts_path %></li>
      <li><%= link_to "News", admin_news_releases_path %></li>
      <li><%= link_to "Appointment Requests", appointments_path %></li>
      <li><%= link_to "Referrals", referrals_path %></li>
    <% end %>

  </ul>

  <p>
    <%= current_user.email %> |
    <%= link_to 'Log Out', session_path, method: :delete %>
  </p>
</div>

app/views/layouts/_analytics.html.erb
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '1853432688098265');
  fbq('track', 'PageView');
</script>

<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1853432688098265&ev=PageView&noscript=1" /></noscript>
<!-- End Facebook Pixel Code -->

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer-outer">
<footer class="site-footer">

  <div class="footer-col">
    <ul>
      <li class="header">Navigation</li>
      <li><%= link_to "Specialties", page_path("specialties") %></li>
      <li><%= link_to "Services", page_path("services") %></li>
      <li><%= link_to "Our Experts", page_path("our-experts") %></li>
      <li><%= link_to "News &amp; Blog".html_safe, news_releases_path %></li>
      <li><%= link_to "Contact Us", page_path("contact-us") %></li>
      <li><%= link_to "About", page_path("about") %></li>
      <li><%= link_to "Patient Resources", page_path("patient-resources") %></li>
      <li><%= link_to "Careers", page_path("careers") %></li>
    </ul>
  </div>

  <div class="footer-col">
    <ul>
      <li class="header">Main Office</li>
      <li>
        University Orthopedics Center<br>
        101 Regent Court<br>
        State College, PA 16801<br>
      </li>
      <li>
      Phone: (814) 231-2101<br>or 1-800-505-2101<br>
        Fax: (814) 231-8569
      </li>
    </ul>
    <ul>
      <li class="header">Other Locations</li>
      <li><%= link_to "View Other Locations", page_path('contact-us') %></li>
    </ul>
  </div>

  <div class="footer-col">
    <ul>
      <li class="header">Phone Numbers</li>
      <li>Appointments<br>(814) 231-2101 or 1-800-505-2101</li>
      <li>Patient Accounts<br>(814) 231-2101 or 1-800-505-2101 </li>
      <li>Medical Records<br>(814) 231-2101 or 1-800-505-2101</li>
      <li>Physical Therapy<br>(814) 231-2101 or 1-800-505-2101 </li>
    </ul>
  </div>

  <div class="footer-col">
    <ul>
      <li class="header">Connect with us</li>
      <li>
        <%= link_to(image_tag("fb_icon.png"), "http://www.facebook.com/UOComeback", target: "_blank") %>
        <%= link_to(image_tag("twitter_icon.png"), "http://www.twitter.com/UOComeback", target: "_blank") %>

        
        <%= link_to(image_tag("instagram-icon.png"), "https://www.instagram.com/uocomeback/", target: "_blank") %>
        <%= link_to(image_tag("g-plus-icon.png"), "https://plus.google.com/b/115754208013700128511/collection/IIAkBE?hl=en", target: "_blank") %>
      </li>
    </ul>

    <ul>
      <li class="header">Online Tools</li>
      <li><%= link_to "Patient Portal", "https://www.nextmd.com/ud2/Login/Login.aspx", target: "_blank" %></li>
      <li><%= link_to "Pay Bill Online", "https://www.nextmd.com/ud2/Login/Login.aspx", target: "_blank" %></li>
      <li><%= link_to "Request an Appointment", page_path('appointments') %></li>
      <li><%= link_to "Referring Physicians", page_path("referring-physicians") %></li>
    </ul>
  </div>

</footer>
</div>

<div class="credits">
  &copy; 2016 University Orthopedics Center 

  <% if current_user %>
    - <%= link_to 'Dashboard', dashboard_path %>
    - <%= link_to 'Log Out', session_path, method: :delete %>
  <% else %>
    - <%= link_to 'Log In', new_session_path %>
  <% end %>

  - <%= link_to "Email Login", "https://mail.uoc.com/owa/auth/logon.aspx?url=https://mail.uoc.com/owa/&reason=0",  target: "_blank" %> 

  - <%= link_to "FWD-PACS", "https://pacs.blairortho.com/ids7/",  target: "_blank" %> 

  <br>
  <%= link_to "Site by Loaded Creative", "http://weareloaded.com", target: "_blank", class: "by-loaded" %> 
</div>

app/views/layouts/_header.html.erb
<header class="site-header">
  <%= link_to(image_tag("logo3.png"), root_path, class: "logo") %>

  <div class="call roboto">
    <h3><span class="call-us">Call Us </span>(814) 231-2101</h3>
    <%= link_to "Make An Appointment", page_path('appointments'), class: "make-appt" %>
    <%= link_to "Pay My Bill", "https://pay.instamed.com/Form/Payments/New?id=uoc", class: "pay-bill", target: "_blank" %>
    <%= link_to "Referring Physicians", page_path('referring-physicians'), class: "referring" %>
  </div>
</header>

app/views/layouts/_login_box.html.erb
<div id="login-box">
  <div class="login-box-col">
    <h3>New Users</h3>
    <p class="login-text">
      I don't have a UOC Patient Portal Account.
    </p>
    <p class="green-button">
      <%= link_to "Create an Account", "https://www.nextmd.com/ud2/Enroll/TermsAndConditions.aspx?enterpriseid=d5b89990-fea1-4bf2-8320-ef7da717cb44", class: "green-link", target: "_new" %>
    </p>
  </div>

  <div class="login-box-col">
    <h3>New Users with Token</h3>
    <p class="login-text">
      I have been issued an enrollment Token and/or a Temporary Username and Password.
    </p>
    <p class="green-button">
      <%= link_to "Create an Account", "https://www.nextmd.com/ud2/Login/Login.aspx", class: "green-link", target: "_new" %>
    </p>
  </div>

  <div class="login-box-col">
    <h3>Existing Users</h3>
    <p class="login-text">
      I already have a UOC Patient Portal Account.
    </p>
    <p class="green-button">
      <%= link_to "Sign In", "https://www.nextmd.com/ud2/Enroll/TermsAndConditions.aspx?enterpriseid=d5b89990-fea1-4bf2-8320-ef7da717cb44", class: "green-link", target: "_new" %>
    </p>
  </div>
</div>


<script>
$(function() {
    $('#patient-login, #login-box').mouseover(function() {
      $('#login-box').show();
    });

    $('#patient-login, #login-box').mouseout(function() {
      $('#login-box').hide();
    });
})
</script>

app/views/layouts/_mobile_footer.html.erb
<div class="footer-outer">
  <footer class="mobile-footer">
    <ul>
      <li class="header">Connect with us</li>
      <li>
        <%= link_to(image_tag("fb_icon.png"), "http://www.facebook.com/UOComeback", target: "_blank") %>
        <%= link_to(image_tag("twitter_icon.png"), "http://www.twitter.com/UOComeback", target: "_blank") %>
      </li>
    </ul>

    <ul>
      <li class="header">Main Office</li>
      <li>
        University Orthopedics Center<br>
        101 Regent Court<br>
        State College, PA 16801<br>
      </li>
      <li>
      Phone: (814) 231-2101<br>or 1-800-505-2101<br>
        Fax: (814) 231-8569
      </li>
    </ul>

  </div>
</div>

<div class="credits">
  &copy; 2016 University Orthopedics Center 
  <br>
  <% if current_user %>
    <%= link_to 'Dashboard', dashboard_path %>
    - <%= link_to 'Log Out', session_path, method: :delete %>
  <% else %>
    <%= link_to 'Log In', new_session_path %>
  <% end %>

  - <%= link_to "Email Login", "https://mail.uoc.com/owa/auth/logon.aspx?url=https://mail.uoc.com/owa/&reason=0",  target: "_blank" %> 

  - <%= link_to "FWD-PACS", "https://pacs.blairortho.com/ids7/",  target: "_blank" %> 

  <br>
  <%= link_to "Site by Loaded Creative", "http://weareloaded.com", target: "_blank", class: "by-loaded" %> 
</div>

app/views/layouts/_mobile_login_box.html.erb
<div id="mobile-login-box">
  <ul>
    <li>
    <div class="group">
    <span class="role">New Users</span> 
      <%= link_to "Create an Account", "https://www.nextmd.com/ud2/Enroll/TermsAndConditions.aspx?enterpriseid=d5b89990-fea1-4bf2-8320-ef7da717cb44", target: "_new" %>
    </div>
  </li>
  <li>
    <div class="group">
    <span class="role">New Users with Token</span>
      <%= link_to "Create an Account", "https://www.nextmd.com/ud2/Login/Login.aspx", target: "_new" %>
    </div>
  </li>
  <li>
    <div class="group">
  <span class="role">Existing Users</span>
      <%= link_to "Sign In", "https://www.nextmd.com/ud2/Enroll/TermsAndConditions.aspx?enterpriseid=d5b89990-fea1-4bf2-8320-ef7da717cb44", target: "_new" %>
    </div>
  </li>
  </ul>
</div>


<script>
$(function() {
    $('#mobile-portal').click(function() {
      $('#mobile-login-box').toggle();
    });
})
</script>

app/views/layouts/_mobile_navigation.html.erb
<nav class="mobile-navigation"> 
  <div class="group">
    <%= link_to "Site Menu", "#", id: "mobile-trigger" %>

    <%= link_to "Patient Log In", "#", id: "mobile-portal" %>

    <%#= link_to "Patient Portal", 
      "https://www.nextmd.com/Login/Login.aspx", 
      id: "mobile-portal", 
      target: "_blank" %>
  </div>

    <ul id="mobile-nav">
      <li>
        <%= link_to "Specialties", "", class: "show-navlist" %>
          <%= render "layouts/sublist", slug: "specialties" %>
      </li>
      <li>
        <%= link_to "Services", "#", class: "show-navlist" %>
          <%= render "layouts/sublist", slug: "services" %>
      </li>
      <li>
      <%= link_to "Our Experts", "#", class: "show-navlist" %>
          <%= render "layouts/experts_sublist" %>
      </li>
      <li>
      <%= link_to "Patient Resources", "#", class: "show-navlist" %>
          <%= render "layouts/sublist", slug: "patient-resources" %>
      </li>
      <li>
      <%= link_to "Contact Us", "#", class: "show-navlist" %>
          <%= render "layouts/sublist", slug: "contact-us" %>
      </li>
    </ul>

</nav>


<%= render "layouts/mobile_login_box" %>


<script>
$(function() {
  $("#mobile-trigger").click(function() {
    $("#mobile-nav").slideToggle();
    //$(this).toggleClass('info-open');
    return false;
  });

  $(".show-navlist").click(function() {
    // open the sublists
    $(this).next('ul').slideToggle();

    // close already opened ones
    $(this).parent().siblings().children().next("ul").slideUp();
    return false;
  });

});
</script>

app/views/layouts/_old_slideshow.html.erb
<div class="feature">
  <div class="cycle-slideshow"
        data-cycle-fx="fadeout" 
        data-cycle-pause-on-hover="true" 
        data-cycle-speed="500"
        data-cycle-timeout="6000"
        data-cycle-slides="> div"
        data-cycle-pager-template="<a href='#'></a>"
        >

    <span class="cycle-pager"></span>

    <div class="slide">
      <div class="slide-image">
        <%= image_tag "UOC_carousel_01.jpg" %>
      </div>
      <div class="slide-copy">
        <h2>Your comeback starts here.</h2>
        <p>
          Whether it’s on the court, the track, the diamond, the field, the rink,
          around the house or on the job, everyone loves a comeback story. At
          University Orthopedics Center, we’re here to help you write yours.
        </p>
        <%= link_to "Start your comeback today", 
          page_path('contact-us'), class: "green-link in-slide" %>
      </div>
    </div>

    <div class="slide">
      <div class="slide-image">
        <%= image_tag "UOC_moving_slide.jpg" %>
      </div>
      <div class="slide-copy">
        <h2>We're growing.</h2>
        <p>University Orthopedics Center is expanding services in Central
        Pennsylvania. Some UOC locations within Altoona and Huntingdon are moving,
        but we’re not going far. We’re also excited to announce our new Ebensburg
        location.</p>
        <%= link_to "See where we're going", 
          'https://www.uoc.com/news_releases/233', class: "green-link in-slide" %>
      </div>
    </div>

    <div class="slide">
      <div class="slide-image">
        <%= image_tag "UOC_carousel_02.jpg" %>
      </div>
      <div class="slide-copy">
        <h2>A more complete approach to care.</h2>
        <p>
         In January of 2016, we joined together with Blair Orthopedics to create
         Central Pennsylvania’s premier orthopedic care center for a better,
         healthier you. 
        </p>
        <%= link_to "Read all about it", 
          news_releases_path, class: "green-link in-slide" %>
      </div>
    </div>


    <div class="slide">
      <div class="slide-image">
        <%= image_tag "UOC_carousel_03.jpg" %>
      </div>
      <div class="slide-copy">
        <h2>Supporting patients every step of the way.</h2>
        <p>
          When it comes to getting you back to better, we specialize in all
        aspects of orthopedic care, including sports medicine, pain management,
        chiropractic care and joint replacement.
        </p>
        <%= link_to "Take your first steps towards better", 
                page_path('specialties'), class: "green-link in-slide" %>
      </div>
    </div>

    <div class="slide">
      <div class="slide-image">
        <%= image_tag "UOC_carousel_04.jpg" %>
      </div>
      <div class="slide-copy">
        <h2>Not all injuries are created equal.</h2>
        <p>
          Each patient’s journey back from injury is unique. When reaching your
          goals means additional resources are needed, we provide a complete
          range of surgical and non-surgical services for recovery.
        </p>
        <%= link_to "Start your journey with us", 
          page_path('services'), class: "green-link in-slide" %>
      </div>
    </div>

    <div class="slide">
      <div class="slide-image">
        <%= image_tag "UOC_carousel_05.jpg" %>
      </div>
      <div class="slide-copy">
        <h2>Helping the best athletes get better.</h2>
        <p>For athletes of every level, injuries and pain are never part of the game
plan. We’re here to help you get back to your peak performance and the
game you love.</p>
        <%= link_to "Your comeback starts now", 
          page_path('sports-medicine-services'), class: "green-link in-slide" %>
      </div>
    </div>


    <div class="slide">
      <div class="slide-image">
        <%= image_tag "UOC_carousel_06.jpg" %>
      </div>
      <div class="slide-copy">
        <h2>The right hands for your care.</h2>
        <p>University Orthopedics Center is home to the region’s top physicians,
        physician assistants, physical therapists, athletic trainers and clinical
        researchers dedicated to helping you live your best life.</p>
        <%= link_to "Meet the experts behind the care", 
          page_path('our-experts'), class: "green-link in-slide" %>
      </div>
    </div>



  </div>
</div>

app/views/layouts/_sub_sublist.html.erb
<% page = Page.find_by(slug: slug) %>

<% if page.nav_list %>
  <ul class="sub-navlist">
    <% page.nav_list.each do |i| %>
      <li>
        <%= link_to i.label, page_path(i.slug), class: "no-arrow" %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_sublist.html.erb
<% page = Page.find_by(slug: slug) %>

<% if page.nav_list %>
  <ul class="navlist">
    <% page.nav_list.each do |i| %>
      <li><%= link_to i.label, page_path(i.slug), class: "no-arrow" %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_top_links.html.erb
<div class="top-links-outer">
  <div class="top-links">
    <ul class="roboto">
      <li><%= link_to "Home", root_path %> &nbsp;&nbsp;|</li>
      <li><%= link_to "About", page_path('about') %> &nbsp;&nbsp;|</li>
      <li><%= link_to "Careers", page_path('careers') %> &nbsp;&nbsp;|</li>
      <li><%= link_to "News &amp; Blog".html_safe, news_releases_path %> </li>
    </ul>
  </div>
</div>

app/views/layouts/_workers_comp_navigation.html.erb
<div class="admin-navigation group">
  <ul>
    <li><%= link_to "Workers Compensation Appointment Requests", appointments_path %></li>
  </ul>

  <p>
    <%= current_user.email %> | 
    <%= link_to 'Log Out', session_path, method: :delete %>
  </p>
</div>